export const COGNITO_VALIDATE_CODE_ENDPOINT = 'https://dm848-project.auth.us-east-1.amazoncognito.com/oauth2/token'
export const COGNITO_LOGIN_ENDPOINT = 'https://dm848-project.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=35juovghcr8nc3m5nbj86ic30g&redirect_uri=https://d3twy8l7wh8x7x.cloudfront.net'
export const COGNITO_REDIRECT_URI = 'https://d3twy8l7wh8x7x.cloudfront.net'
export const APP_CLIENT_ID = '35juovghcr8nc3m5nbj86ic30g'
export const MICROSERVICES_API = 'http://35.228.7.206:8888/'
export const DASHBOARD_TEST_CONTENT = 'https://d3twy8l7wh8x7x.cloudfront.net/test.txt'
